name: Elbram
version: '${project.version}'
main: fr.kazotaruumc72.elbram.Elbram
api-version: '1.21'
description: Système de connaissances joueurs

depend:
  - Quantum

commands:
  elbram:
    description: Commande principale d'Elbram
    usage: /elbram <apprendre|reload>
    aliases: [elb]
  profil:
    description: Ouvre le menu de connaissances du joueur
    usage: /profil
  apprendre:
    description: Transmet une Information à un autre joueur (échange asymétrique)
    usage: /apprendre <joueur> <connaissance>

permissions:
  elbram.apprendre:
    description: Recevoir le livre de connaissances
    default: op
  elbram.admin:
    description: Accès aux commandes d'administration
    default: op
  elbram.teach:
    description: Transmettre une Information à un autre joueur via /apprendre
    default: true
  elbram.informations.tours:
    description: Accès aux informations sur les tours
    default: false
  elbram.informations.construction:
    description: Accès aux informations sur la construction
    default: false
  elbram.informations.combat:
    description: Accès aux informations sur le combat
    default: false
  elbram.informations.exploration:
    description: Accès aux informations sur l'exploration
    default: false
